include: package:very_good_analysis/analysis_options.5.1.0.yaml

linter:
  rules:
    always_use_package_imports: false
    one_member_abstracts: false
    unnecessary_lambdas: false
    public_member_api_docs: false
    avoid_equals_and_hash_code_on_mutable_classes: false
