name: fake_store_client
description: Fetch to API Fake Store
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.5.0+1
  talker: ^4.4.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.7
  very_good_analysis: ^6.0.0
